version: '3.7'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - "3001:3000"
    networks:
      - backend
      
  db:
    container_name: db
    image: "postgres"
    ports: 
      - "5431:5432"
    restart: always
    networks:
      - backend

networks:
  backend:
    name: backend
  
