version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - "3001:3000"
    networks:
      - backend
    volumes:
      - ./api:/usr/src/app
    env_file: .env
      
  db:
    image: "postgres"
    ports: 
      - "5431:5432"
    restart: always
    networks:
      - backend
    volumes:
      - ./Temp/postgres:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    env_file: .env

networks:
  backend:
    name: backend
  
