version: '3.7'
services:
    api:
      environment: 
        - POSTGRES_PASSWORD
        - POSTGRES_USER
    db:
      environment: 
        - POSTGRES_PASSWORD
        - POSTGRES_USER
      volumes:
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro    