name: CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}

    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
    - name: Check running containers
      run: docker ps -a
    - name: Check API logs
      run: docker logs api
    - name: Check DB logs
      run: docker logs db            
    - name: Run test suite
      run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml run --rm api npm run test:unit --watch
